# Generated by Django 5.2 on 2025-05-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
    ]
